name: WayPointChat
version: '${project.version}'
main: me.branchyz.waypointchat.WayPointChat
api-version: 1.18
authors: [ Branchyz, WayPoint ]
depend: [CommandAPI]
commands:
  broadcast:
    aliases: [bc]
    description: "This command broadcasts a message!"
  mutechat:
    aliases: [unmutechat]
    description: "This command mutes the chat!"
  clearchat:
    description: "This command clears the chat!"
  countdown:
    aliases: [cd]
    description: "This command starts or stops a countdown!"

permissions:
  waypoint.alert:
    description: "Players with this permission will receive an alert when someone uses a curse word!"
  waypoint.broadcast:
    description: "With this permission you have access to the broadcast command!"
  waypoint.mutechat:
    description: "With this permission you have access to the mutechat command!"
  waypoint.mutechat.bypass:
    description: "With this permission, you can still chat when the chat is muted!"
  waypoint.clearchat:
    description: "With this permission you have access to the clearchat command!"
  waypoint.countdown:
    description: "With this permission you have access to the countdown command!"