name: WayPointChat
version: ${project.version}
main: me.branchyz.waypointchat.WayPointChat
authors: [ Branchyz, WayPoint ]
softdepend: [CommandAPI]

commands:
  broadcast:
    aliases: [bc]
    description: "This command broadcasts a message!"
  mutechat:
    aliases: [unmutechat]
    description: "This command mutes the chat!"
  clearchat:
    description: "This command clears the chat!"
  countdown:
    aliases: [cd]
    description: "This command starts or stops a countdown!"

permissions:
  waypoint.*:
    description: "Players with this permission can do everything!"
  waypoint.cursewords.alert:
    description: "Players with this permission will receive an alert when someone uses a curse word!"
  waypoint.cursewords.bypass:
    description: "Players with this permission can bypass the curse words system!"
  waypoint.broadcast:
    description: "With this permission you have access to the broadcast command!"
  waypoint.mutechat:
    description: "With this permission you have access to the mutechat command!"
  waypoint.mutechat.bypass:
    description: "With this permission, you can still chat when the chat is muted!"
  waypoint.clearchat:
    description: "With this permission you have access to the clearchat command!"
  waypoint.countdown:
    description: "With this permission you have access to the countdown command!"
  waypoint.version:
    description: "With this permission you will be notified when a new version is available!"